#!/usr/bin/env python3
"""Heuristic, read-only comment inventory. It never edits files."""

from __future__ import annotations

import argparse
import re
from pathlib import Path

SKIP_DIRS = {
    ".git",
    ".hg",
    ".svn",
    "build",
    "dist",
    "node_modules",
    "target",
    "vendor",
    "vendored",
}
TEXT_EXTENSIONS = {
    ".c",
    ".cc",
    ".cpp",
    ".css",
    ".go",
    ".h",
    ".hpp",
    ".html",
    ".java",
    ".js",
    ".jsx",
    ".mjs",
    ".py",
    ".rb",
    ".res",
    ".resi",
    ".rs",
    ".sh",
    ".svg",
    ".ts",
    ".tsx",
    ".xml",
}
GENERATED_MARKERS = (
    "@generated",
    "automatically generated",
    "autogenerated",
    "do not edit",
    "generated file",
)


def files_under(targets: list[Path]):
    seen: set[Path] = set()
    for target in targets:
        candidates = [target] if target.is_file() else target.rglob("*")
        for path in candidates:
            if not path.is_file() or path in seen:
                continue
            if any(part in SKIP_DIRS for part in path.parts):
                continue
            if path.suffix.lower() not in TEXT_EXTENSIONS:
                continue
            seen.add(path)
            yield path


def candidate_lines(text: str, suffix: str) -> int:
    lines = text.splitlines()
    if suffix in {".py", ".rb", ".sh"}:
        return sum(line.lstrip().startswith("#") and not line.startswith("#!") for line in lines)
    if suffix in {".html", ".xml", ".svg"}:
        return sum(len(match.group(0).splitlines()) for match in re.finditer(r"<!--.*?-->", text, re.S))
    if suffix == ".css":
        return sum(len(match.group(0).splitlines()) for match in re.finditer(r"/\*.*?\*/", text, re.S))
    line_comments = sum(line.lstrip().startswith("//") for line in lines)
    block_comments = sum(
        len(match.group(0).splitlines()) for match in re.finditer(r"/\*.*?\*/", text, re.S)
    )
    return line_comments + block_comments


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("targets", nargs="+", type=Path)
    args = parser.parse_args()

    rows = []
    for path in files_under(args.targets):
        try:
            text = path.read_text()
        except (OSError, UnicodeError):
            continue
        header = "\n".join(text.splitlines()[:10]).lower()
        generated = "generated?" if any(marker in header for marker in GENERATED_MARKERS) else ""
        rows.append((candidate_lines(text, path.suffix.lower()), len(text.splitlines()), generated, path))

    print(f"{'comments':>8} {'lines':>8} {'classification':>14}  path")
    for comments, lines, generated, path in sorted(rows, key=lambda row: (-row[0], str(row[3]))):
        print(f"{comments:8} {lines:8} {generated:>14}  {path}")
    print(f"\n{sum(row[0] for row in rows)} candidate comment lines in {len(rows)} text files")
    print("Heuristic only: inspect strings, fixtures, directives, licenses, and generated files manually.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
